### ISSUE TITLE
Squeezenet backbone

### ISSUE THREAD

**Issue by waynehuu** [bohaohuang/mrs#2]
Add [SqueezeNet](https://github.com/pytorch/vision/blob/master/torchvision/models/squeezenet.py)
- [x] UNet, PSPNet, LinkNet compatability
- [x] SqueezeNet + Unet on Inria toyset
- [x] SqueezeNet + Unet on Inria buildings
- [x] Dilation

**Comment by bohaohuang** [comment]
Add [SqueezeNet](https://github.com/pytorch/vision/blob/master/torchvision/models/squeezenet.py)
- [ ] UNet, PSPNet, LinkNet compatability
- [ ] SqueezeNet + Unet on Inria toyset
- [ ] SqueezeNet + Unet on Inria buildings
