### ISSUE TITLE
Object-based Scoring

### ISSUE THREAD

**Issue by waynehuu** [bohaohuang/mrs#5]
Object-based scoring method
- [x] Confmap parsing function
- [x] Object link function
- [x] PR scoring
- [x] mAP versus link radius

**Comment by bohaohuang** [comment]
Method implemented in #30 , will add a jupyter notebook demonstrating the process
@waynehuu Do you think it would be more resonable if we move the evaluating function currently in network_utils.py to this new eval_utils.py? If you agree I'll create a new PR and we can review that together.

**Comment by waynehuu** [comment]
> Method implemented in #30 , will add a jupyter notebook demonstrating the process
> @waynehuu Do you think it would be more resonable if we move the evaluating function currently in network_utils.py to this new eval_utils.py? If you agree I'll create a new PR and we can review that together.

Sorry I just saw this. I think it's reasonable.

**Comment by bohaohuang** [comment]
Example script updated in #31
