### ISSUE TITLE
Add a "further train" mode ?

### ISSUE THREAD

**Issue by waynehuu** [bohaohuang/mrs#50]
- "resume_epoch" is used when the pre-defined number of epochs of training isn't completed. A model's state dict and the optimizer will be loaded from a snapshot. config["trainer"]["resume_epoch"] has to be no greater than config["trainer"]["epochs"].
- Fine-tuning is for a new dataset and the optimizer will be re-initialized.
- "further train" is for situations where the finished training is deemed insufficient and we want to train for some more epochs from a snapshot model without re-initializing the optimizer. Basically this is equivalent to fine-tuning but with network_utils.load_epoch() in stead of network_utils.load()

@bohaohuang let me know if this makes sense to you.

**Comment by bohaohuang** [comment]
I created a PR in #51 , please review it and let me know if this is what you want.
Also, the process is now making train.py a littble bit messy, so suggestions are welcome for clearning up the entry file.

**Comment by waynehuu** [comment]
> I created a PR in #51 , please review it and let me know if this is what you want.
> Also, the process is now making train.py a littble bit messy, so suggestions are welcome for clearning up the entry file.

I have a local implementation and I have jobs running right now. I might have a few changes to make and I'll commit them after testing.
